// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCTS7kb245Z5AyzL0DrTx-75lNvgEc-pQ',
    appId: '1:113245100333:web:d724e7d017ca7117f35ba4',
    messagingSenderId: '113245100333',
    projectId: 'ubixstar-59614',
    authDomain: 'ubixstar-59614.firebaseapp.com',
    storageBucket: 'ubixstar-59614.appspot.com',
    measurementId: 'G-SB62QC77RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEbk82_-q-oYlvs0UFuLaACFZc9iAEX8',
    appId: '1:113245100333:android:1257e95743d1ad2bf35ba4',
    messagingSenderId: '113245100333',
    projectId: 'ubixstar-59614',
    storageBucket: 'ubixstar-59614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxUBLXmYqn4_yObkBlWY85VJimxfOb_fA',
    appId: '1:113245100333:ios:15cd848fc16a70a4f35ba4',
    messagingSenderId: '113245100333',
    projectId: 'ubixstar-59614',
    storageBucket: 'ubixstar-59614.appspot.com',
    iosBundleId: 'com.example.ubixstarAssignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxUBLXmYqn4_yObkBlWY85VJimxfOb_fA',
    appId: '1:113245100333:ios:a0f782bcabb5c9ecf35ba4',
    messagingSenderId: '113245100333',
    projectId: 'ubixstar-59614',
    storageBucket: 'ubixstar-59614.appspot.com',
    iosBundleId: 'com.example.ubixstarAssignmentApp.RunnerTests',
  );
}
